"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const auth_middleware_1 = require("../middleware/auth.middleware");
const course_routes_1 = __importDefault(require("./course.routes"));
const dashboard_routes_1 = __importDefault(require("./dashboard.routes"));
const lesson_routes_1 = __importDefault(require("./lesson.routes"));
const room_routes_1 = __importDefault(require("./room.routes"));
const score_routes_1 = __importDefault(require("./score.routes"));
const teacher_router_1 = require("./teacher.router");
const user_routes_1 = __importDefault(require("./user.routes"));
const video_routes_1 = __importDefault(require("./video.routes"));
const router = express_1.default.Router();
router.use("/user", user_routes_1.default);
router.use("/score", auth_middleware_1.AuthMiddleware, score_routes_1.default);
router.use("/course", auth_middleware_1.AuthMiddleware, course_routes_1.default);
router.use("/room", auth_middleware_1.AuthMiddleware, room_routes_1.default);
router.use("/video", auth_middleware_1.AuthMiddleware, video_routes_1.default);
router.use("/dashboard", auth_middleware_1.AuthMiddleware, dashboard_routes_1.default);
router.use("/lesson", auth_middleware_1.AuthMiddleware, lesson_routes_1.default);
router.use("/teacher", auth_middleware_1.AuthMiddleware, teacher_router_1.teacherRouter);
exports.default = router;
